spring:
  main:
    web-application-type: reactive
    banner-mode: off
  ai:
    mcp:
      server:
        name: resume-scanner-mcp-server
        version: 1.0.0
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-5.4

server:
  port: 8083
  address: 0.0.0.0

logging:
  level:
    root: INFO
